---
title: IRZ
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    author_profile: false
    read_time: true
    comments: true
    share: true
    related: true
    author: art
- scope:
    path: ''
    type: pages
  values:
    layout: single
    author_profile: false
    read_time: true
    comments: true
    share: true
    related: true
minimal_mistakes_skin: default
locale: fr
title_img: assets/img/logo.svg
title_separator: "-"
name: art
description: Inspiration, réflexion, et partage du savoir
url: https://irz.fr
baseurl: 
repository: arthurlacoste/irz.fr
teaser: 
words_per_minute: 170
comments:
  provider: staticman_v2
  disqus:
    shortname: 
  discourse:
    server: 
  facebook:
    appid: 
    num_posts: 
    colorscheme: 
staticman:
  allowedFields:
  - name
  - email
  - url
  - message
  branch: gh-pages
  commitMessage: New comment.
  filename: comment-{@timestamp}
  format: yml
  moderation: true
  path: "/_data/comments/{options.slug}"
  requiredFields:
  - name
  - email
  - message
  transforms:
    email: md5
  generatedFields:
    date:
      type: date
      options:
        format: 
reCaptcha:
  siteKey: 6LfhwjgUAAAAAKe-NJJoSThrjQYCL-TpO5h8oXvH
  secret: tBSOyntwF4JAoOvzfbOoDCx3XIi+Ts07RjVXwAdCCYjmN8N7v17qIxr9RpgAf5VMpaWhgp1dYVZ566JcKYV58037lO59yCP/InvbL6d8vxPRWzlSB+k3wXa+uBWZ7ttQiVjV7OdNfJQTF74accijyFLu1EAqfftb8pbjUWiGUX0=
atom_feed:
  path: 
google_site_verification: 
bing_site_verification: 
alexa_site_verification: 
yandex_site_verification: 
naver-site-verification: 
twitter:
  username: arthurlacoste
facebook:
  username: 
  app_id: 
  publisher: 
og_image: assets/img/logo-og-irz.png
social:
  type: 
  name: 
  links: 
analytics:
  provider: google
  google:
    tracking_id: UA-5025145-5
author:
  name: art
  avatar: "/assets/img/me.jpg"
  bio: Trafiquant de rêves.
  location: Grenoble, France
  email: 
  uri: http://arthurlacoste.com
  bitbucket: 
  codepen: 
  dribbble: 
  flickr: 
  facebook: irz.fr
  foursquare: 
  github: arthurlacoste
  gitlab: 
  google_plus: 
  keybase: 
  instagram: arthak
  lastfm: 
  linkedin: 
  pinterest: 
  soundcloud: 
  stackoverflow: 
  steam: 
  tumblr: 
  twitter: arthurlacoste
  mastodon: https://mastodon.social/@arthak
  vine: 
  weibo: 
  xing: 
  youtube: https://www.youtube.com/user/lacostearthur
include:
- ".htaccess"
- _pages
exclude:
- "*.sublime-project"
- "*.sublime-workspace"
- vendor
- ".asset-cache"
- ".bundle"
- ".jekyll-assets-cache"
- ".sass-cache"
- assets/js/plugins
- assets/js/_main.js
- assets/js/vendor
- Capfile
- CHANGELOG
- config
- Gemfile
- Gruntfile.js
- gulpfile.js
- LICENSE
- log
- node_modules
- package.json
- Rakefile
- README
- tmp
- "/docs"
- "/test"
keep_files:
- ".git"
- ".svn"
encoding: utf-8
markdown_ext: markdown,mkdown,mkdn,mkd,md
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
sass:
  sass_dir: _sass
  style: compressed
permalink: "/:slug"
paginate: 20
paginate_path: "/page:num/"
plugins:
- jekyll-redirect-from
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jemoji
whitelist:
- jekyll-redirect-from
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jemoji
category_archive:
  type: liquid
  path: "/categories/"
tag_archive:
  type: liquid
  path: "/tags/"
compress_html:
  clippings: all
  ignore:
    envs: development
tipue_search:
  include:
    pages: true
    collections: 
